### ISSUE TITLE
Some simple mistakes

### ISSUE THREAD

**Issue by f0rm2l1n** [De1ta-team/De1CTF2019#2]
https://github.com/De1ta-team/De1CTF2019/tree/master/writeup/misc/Easy%20EOS

When explaining **Roll Back Attack** and **Pseudo random number**

The folders are wrong named.
Seems the right order is
`Roll Back Attack -> attack4`
`Pseudo random number -> attack`

**Comment by UltramanGaia** [comment]
Ooops! Thanks. I appreciate your help.
Fixed in cc10a8f6e173513e94111275c1591119beec1705
