### ISSUE TITLE
something strange

### ISSUE THREAD

**Issue by zeenanqaq** [De1ta-team/De1CTF2019#3]
In the solution to the **xorz** challenge
> It is basically a transformed vigenere.
> There is no original idea ,and all codes are my own.
> 
> 可看作变种的维吉尼亚密码，因为明文是有意义的一段话，由可见字符构成，所以可遍历得到可能的key长度和字符集。
> idea均源自网络，题干与解题脚本代码均为原创。
![something_strange.png](https://i.loli.net/2019/08/06/HY81GEkF965XZpu.png)
I'm wondering what are you trying to express?
What's worse? I've seen **the exact same code before**
[link](https://blog.csdn.net/w12315q/article/details/83999770)

---

In the solution to the **Obscured** chllenge
![strange_solution.png](https://i.loli.net/2019/08/06/PCnDSz9IZrXYqeu.png)
Hey, bro! How do you get this relational expression?

---

By the way, next time you distribute the challenge code, **Reformat** it!!!!!

**Comment by aye-whitehat** [comment]
This code is the author of xorz's code, : )
https://blog.csdn.net/w12315q/article/details/83999770

**Comment by aye-whitehat** [comment]
> In the solution to the **xorz** challenge
> 
> > It is basically a transformed vigenere.
> > There is no original idea ,and all codes are my own.
> > 可看作变种的维吉尼亚密码，因为明文是有意义的一段话，由可见字符构成，所以可遍历得到可能的key长度和字符集。
> > idea均源自网络，题干与解题脚本代码均为原创。
> > ![something_strange.png](https://camo.githubusercontent.com/3c7c3c46c04a73cdeda83bd9ab6c65ca6083816b/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30382f30362f4859383147456b46393635585a70752e706e67)
> > I'm wondering what are you trying to express?
> > What's worse? I've seen **the exact same code before**
> > [link](https://blog.csdn.net/w12315q/article/details/83999770)
> 
> In the solution to the **Obscured** chllenge
> ![strange_solution.png](https://camo.githubusercontent.com/0502c66346889d5441484fa59fb9a99bf3398bf4/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30382f30362f50436e44537a39495a7258597165752e706e67)
> Hey, bro! How do you get this relational expression?
> 
> By the way, next time you distribute the challenge code, **Reformat** it!!!!!

This code is the author's code : )
https://blog.csdn.net/w12315q/article/details/83999770
https://findneo.github.io/
![image](https://user-images.githubusercontent.com/37626950/62543104-c5cea880-b88f-11e9-92d7-f729c3e8ac0f.png)

**Comment by zeenanqaq** [comment]
First of all, I apologize for the groundless accusation. But I didn't mean to emphasize the plagiarism of the code (from my point of view, I don't think that's a problem, anyway it's not very realistic to implement everything by your own), it's just that the two versions of writeups don't express the same meaning, and the emphasis for the "own code" seems strange...2333

**Comment by gmcnqaq** [comment]
First of all, I apologize for the groundless accusation. But I didn't mean to emphasize the plagiarism of the code (from my point of view, I don't think that's a problem, anyway it's not very realistic to implement everything by your own), it's just that the two versions of writeups don't express the same meaning, and the emphasis for the "own code" seems strange...2333
