### ISSUE TITLE
Viruses danger!

### ISSUE THREAD

**Issue by wuyuansushen** [De1ta-team/De1CTF2019#4]
The Windows Defender have warned this zip (/wp/re/Re_sign/Re_sign.zip).It  extracts the .exe is dangerous!

> Program:Win32/Unwaders.A!ml
warning level:serious
detail:This program maybe do some harmful options.
file: E:\Download\Re_Sign\re sign.exe

**Comment by t3hp0rP** [comment]
If you worry about this, please run it under virtual machine.
